// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.1
//
namespace Loewenbraeu.Data.Service {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="Service1Soap", Namespace="http://loewenbraeuservice.ip-connect.de/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TodaysMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReservationByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateReservationByObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReservationConfirmOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsDeclinedByRestaurantOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReservationConfirmCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDecliningOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReservationsByStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPicturesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVideosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQuestionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQuizOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivateVoucherOperationCompleted;
        
        private System.Threading.SendOrPostCallback DischargeVoucherOperationCompleted;
        
        public Service1() {
            this.Url = "https://lbkmobile.loewenbraeukeller.com/service/service1.asmx";
        }
        
        public event TodaysMenuCompletedEventHandler TodaysMenuCompleted;
        
        public event CreateReservationCompletedEventHandler CreateReservationCompleted;
        
        public event GetReservationByIdCompletedEventHandler GetReservationByIdCompleted;
        
        public event CreateReservationByObjectCompletedEventHandler CreateReservationByObjectCompleted;
        
        public event SetReservationConfirmCompletedEventHandler SetReservationConfirmCompleted;
        
        public event IsDeclinedByRestaurantCompletedEventHandler IsDeclinedByRestaurantCompleted;
        
        public event SetReservationConfirmCustomerCompletedEventHandler SetReservationConfirmCustomerCompleted;
        
        public event SetDecliningCompletedEventHandler SetDecliningCompleted;
        
        public event GetReservationsByStatusCompletedEventHandler GetReservationsByStatusCompleted;
        
        public event GetEventsCompletedEventHandler GetEventsCompleted;
        
        public event GetPicturesCompletedEventHandler GetPicturesCompleted;
        
        public event GetVideosCompletedEventHandler GetVideosCompleted;
        
        public event GetQuestionCompletedEventHandler GetQuestionCompleted;
        
        public event GetQuizCompletedEventHandler GetQuizCompleted;
        
        public event ActivateVoucherCompletedEventHandler ActivateVoucherCompleted;
        
        public event DischargeVoucherCompletedEventHandler DischargeVoucherCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/TodaysMenu", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public DishesOfTheDay TodaysMenu(string requestedDate, string fingerprint) {
            object[] results = this.Invoke("TodaysMenu", new object[] {
                        requestedDate,
                        fingerprint});
            return ((DishesOfTheDay)(results[0]));
        }
        
        public System.IAsyncResult BeginTodaysMenu(string requestedDate, string fingerprint, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TodaysMenu", new object[] {
                        requestedDate,
                        fingerprint}, callback, asyncState);
        }
        
        public DishesOfTheDay EndTodaysMenu(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DishesOfTheDay)(results[0]));
        }
        
        public void TodaysMenuAsync(string requestedDate, string fingerprint) {
            this.TodaysMenuAsync(requestedDate, fingerprint, null);
        }
        
        public void TodaysMenuAsync(string requestedDate, string fingerprint, object userState) {
            if ((this.TodaysMenuOperationCompleted == null)) {
                this.TodaysMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodaysMenuCompleted);
            }
            this.InvokeAsync("TodaysMenu", new object[] {
                        requestedDate,
                        fingerprint}, this.TodaysMenuOperationCompleted, userState);
        }
        
        private void OnTodaysMenuCompleted(object arg) {
            if ((this.TodaysMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodaysMenuCompleted(this, new TodaysMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/CreateReservation", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string CreateReservation(string when, int seats, string mobile, string fingerprint, string name, string advice, string confirmcode) {
            object[] results = this.Invoke("CreateReservation", new object[] {
                        when,
                        seats,
                        mobile,
                        fingerprint,
                        name,
                        advice,
                        confirmcode});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginCreateReservation(string when, int seats, string mobile, string fingerprint, string name, string advice, string confirmcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateReservation", new object[] {
                        when,
                        seats,
                        mobile,
                        fingerprint,
                        name,
                        advice,
                        confirmcode}, callback, asyncState);
        }
        
        public string EndCreateReservation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void CreateReservationAsync(string when, int seats, string mobile, string fingerprint, string name, string advice, string confirmcode) {
            this.CreateReservationAsync(when, seats, mobile, fingerprint, name, advice, confirmcode, null);
        }
        
        public void CreateReservationAsync(string when, int seats, string mobile, string fingerprint, string name, string advice, string confirmcode, object userState) {
            if ((this.CreateReservationOperationCompleted == null)) {
                this.CreateReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateReservationCompleted);
            }
            this.InvokeAsync("CreateReservation", new object[] {
                        when,
                        seats,
                        mobile,
                        fingerprint,
                        name,
                        advice,
                        confirmcode}, this.CreateReservationOperationCompleted, userState);
        }
        
        private void OnCreateReservationCompleted(object arg) {
            if ((this.CreateReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateReservationCompleted(this, new CreateReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/GetReservationById", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Reservation GetReservationById(string reservationId) {
            object[] results = this.Invoke("GetReservationById", new object[] {
                        reservationId});
            return ((Reservation)(results[0]));
        }
        
        public System.IAsyncResult BeginGetReservationById(string reservationId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReservationById", new object[] {
                        reservationId}, callback, asyncState);
        }
        
        public Reservation EndGetReservationById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Reservation)(results[0]));
        }
        
        public void GetReservationByIdAsync(string reservationId) {
            this.GetReservationByIdAsync(reservationId, null);
        }
        
        public void GetReservationByIdAsync(string reservationId, object userState) {
            if ((this.GetReservationByIdOperationCompleted == null)) {
                this.GetReservationByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReservationByIdCompleted);
            }
            this.InvokeAsync("GetReservationById", new object[] {
                        reservationId}, this.GetReservationByIdOperationCompleted, userState);
        }
        
        private void OnGetReservationByIdCompleted(object arg) {
            if ((this.GetReservationByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReservationByIdCompleted(this, new GetReservationByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/CreateReservationByObject", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string CreateReservationByObject(Reservation tmpReservation) {
            object[] results = this.Invoke("CreateReservationByObject", new object[] {
                        tmpReservation});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginCreateReservationByObject(Reservation tmpReservation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateReservationByObject", new object[] {
                        tmpReservation}, callback, asyncState);
        }
        
        public string EndCreateReservationByObject(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void CreateReservationByObjectAsync(Reservation tmpReservation) {
            this.CreateReservationByObjectAsync(tmpReservation, null);
        }
        
        public void CreateReservationByObjectAsync(Reservation tmpReservation, object userState) {
            if ((this.CreateReservationByObjectOperationCompleted == null)) {
                this.CreateReservationByObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateReservationByObjectCompleted);
            }
            this.InvokeAsync("CreateReservationByObject", new object[] {
                        tmpReservation}, this.CreateReservationByObjectOperationCompleted, userState);
        }
        
        private void OnCreateReservationByObjectCompleted(object arg) {
            if ((this.CreateReservationByObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateReservationByObjectCompleted(this, new CreateReservationByObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/SetReservationConfirm", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool SetReservationConfirm(string reservationId) {
            object[] results = this.Invoke("SetReservationConfirm", new object[] {
                        reservationId});
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginSetReservationConfirm(string reservationId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetReservationConfirm", new object[] {
                        reservationId}, callback, asyncState);
        }
        
        public bool EndSetReservationConfirm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        public void SetReservationConfirmAsync(string reservationId) {
            this.SetReservationConfirmAsync(reservationId, null);
        }
        
        public void SetReservationConfirmAsync(string reservationId, object userState) {
            if ((this.SetReservationConfirmOperationCompleted == null)) {
                this.SetReservationConfirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReservationConfirmCompleted);
            }
            this.InvokeAsync("SetReservationConfirm", new object[] {
                        reservationId}, this.SetReservationConfirmOperationCompleted, userState);
        }
        
        private void OnSetReservationConfirmCompleted(object arg) {
            if ((this.SetReservationConfirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReservationConfirmCompleted(this, new SetReservationConfirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/IsDeclinedByRestaurant", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool IsDeclinedByRestaurant(string reservationId) {
            object[] results = this.Invoke("IsDeclinedByRestaurant", new object[] {
                        reservationId});
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginIsDeclinedByRestaurant(string reservationId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsDeclinedByRestaurant", new object[] {
                        reservationId}, callback, asyncState);
        }
        
        public bool EndIsDeclinedByRestaurant(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        public void IsDeclinedByRestaurantAsync(string reservationId) {
            this.IsDeclinedByRestaurantAsync(reservationId, null);
        }
        
        public void IsDeclinedByRestaurantAsync(string reservationId, object userState) {
            if ((this.IsDeclinedByRestaurantOperationCompleted == null)) {
                this.IsDeclinedByRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsDeclinedByRestaurantCompleted);
            }
            this.InvokeAsync("IsDeclinedByRestaurant", new object[] {
                        reservationId}, this.IsDeclinedByRestaurantOperationCompleted, userState);
        }
        
        private void OnIsDeclinedByRestaurantCompleted(object arg) {
            if ((this.IsDeclinedByRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsDeclinedByRestaurantCompleted(this, new IsDeclinedByRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/SetReservationConfirmCustomer", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool SetReservationConfirmCustomer(string reservationId) {
            object[] results = this.Invoke("SetReservationConfirmCustomer", new object[] {
                        reservationId});
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginSetReservationConfirmCustomer(string reservationId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetReservationConfirmCustomer", new object[] {
                        reservationId}, callback, asyncState);
        }
        
        public bool EndSetReservationConfirmCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        public void SetReservationConfirmCustomerAsync(string reservationId) {
            this.SetReservationConfirmCustomerAsync(reservationId, null);
        }
        
        public void SetReservationConfirmCustomerAsync(string reservationId, object userState) {
            if ((this.SetReservationConfirmCustomerOperationCompleted == null)) {
                this.SetReservationConfirmCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReservationConfirmCustomerCompleted);
            }
            this.InvokeAsync("SetReservationConfirmCustomer", new object[] {
                        reservationId}, this.SetReservationConfirmCustomerOperationCompleted, userState);
        }
        
        private void OnSetReservationConfirmCustomerCompleted(object arg) {
            if ((this.SetReservationConfirmCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReservationConfirmCustomerCompleted(this, new SetReservationConfirmCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/SetDeclining", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool SetDeclining(string reservationId) {
            object[] results = this.Invoke("SetDeclining", new object[] {
                        reservationId});
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginSetDeclining(string reservationId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetDeclining", new object[] {
                        reservationId}, callback, asyncState);
        }
        
        public bool EndSetDeclining(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        public void SetDecliningAsync(string reservationId) {
            this.SetDecliningAsync(reservationId, null);
        }
        
        public void SetDecliningAsync(string reservationId, object userState) {
            if ((this.SetDecliningOperationCompleted == null)) {
                this.SetDecliningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDecliningCompleted);
            }
            this.InvokeAsync("SetDeclining", new object[] {
                        reservationId}, this.SetDecliningOperationCompleted, userState);
        }
        
        private void OnSetDecliningCompleted(object arg) {
            if ((this.SetDecliningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDecliningCompleted(this, new SetDecliningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/GetReservationsByStatus", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Reservation[] GetReservationsByStatus(int status) {
            object[] results = this.Invoke("GetReservationsByStatus", new object[] {
                        status});
            return ((Reservation[])(results[0]));
        }
        
        public System.IAsyncResult BeginGetReservationsByStatus(int status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReservationsByStatus", new object[] {
                        status}, callback, asyncState);
        }
        
        public Reservation[] EndGetReservationsByStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Reservation[])(results[0]));
        }
        
        public void GetReservationsByStatusAsync(int status) {
            this.GetReservationsByStatusAsync(status, null);
        }
        
        public void GetReservationsByStatusAsync(int status, object userState) {
            if ((this.GetReservationsByStatusOperationCompleted == null)) {
                this.GetReservationsByStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReservationsByStatusCompleted);
            }
            this.InvokeAsync("GetReservationsByStatus", new object[] {
                        status}, this.GetReservationsByStatusOperationCompleted, userState);
        }
        
        private void OnGetReservationsByStatusCompleted(object arg) {
            if ((this.GetReservationsByStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReservationsByStatusCompleted(this, new GetReservationsByStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/GetEvents", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Event[] GetEvents(string fingerprint) {
            object[] results = this.Invoke("GetEvents", new object[] {
                        fingerprint});
            return ((Event[])(results[0]));
        }
        
        public System.IAsyncResult BeginGetEvents(string fingerprint, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEvents", new object[] {
                        fingerprint}, callback, asyncState);
        }
        
        public Event[] EndGetEvents(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Event[])(results[0]));
        }
        
        public void GetEventsAsync(string fingerprint) {
            this.GetEventsAsync(fingerprint, null);
        }
        
        public void GetEventsAsync(string fingerprint, object userState) {
            if ((this.GetEventsOperationCompleted == null)) {
                this.GetEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventsCompleted);
            }
            this.InvokeAsync("GetEvents", new object[] {
                        fingerprint}, this.GetEventsOperationCompleted, userState);
        }
        
        private void OnGetEventsCompleted(object arg) {
            if ((this.GetEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEventsCompleted(this, new GetEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/GetPictures", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Picture[] GetPictures(string fingerprint) {
            object[] results = this.Invoke("GetPictures", new object[] {
                        fingerprint});
            return ((Picture[])(results[0]));
        }
        
        public System.IAsyncResult BeginGetPictures(string fingerprint, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPictures", new object[] {
                        fingerprint}, callback, asyncState);
        }
        
        public Picture[] EndGetPictures(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Picture[])(results[0]));
        }
        
        public void GetPicturesAsync(string fingerprint) {
            this.GetPicturesAsync(fingerprint, null);
        }
        
        public void GetPicturesAsync(string fingerprint, object userState) {
            if ((this.GetPicturesOperationCompleted == null)) {
                this.GetPicturesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPicturesCompleted);
            }
            this.InvokeAsync("GetPictures", new object[] {
                        fingerprint}, this.GetPicturesOperationCompleted, userState);
        }
        
        private void OnGetPicturesCompleted(object arg) {
            if ((this.GetPicturesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPicturesCompleted(this, new GetPicturesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/GetVideos", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Video[] GetVideos(string fingerprint) {
            object[] results = this.Invoke("GetVideos", new object[] {
                        fingerprint});
            return ((Video[])(results[0]));
        }
        
        public System.IAsyncResult BeginGetVideos(string fingerprint, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetVideos", new object[] {
                        fingerprint}, callback, asyncState);
        }
        
        public Video[] EndGetVideos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Video[])(results[0]));
        }
        
        public void GetVideosAsync(string fingerprint) {
            this.GetVideosAsync(fingerprint, null);
        }
        
        public void GetVideosAsync(string fingerprint, object userState) {
            if ((this.GetVideosOperationCompleted == null)) {
                this.GetVideosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVideosCompleted);
            }
            this.InvokeAsync("GetVideos", new object[] {
                        fingerprint}, this.GetVideosOperationCompleted, userState);
        }
        
        private void OnGetVideosCompleted(object arg) {
            if ((this.GetVideosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVideosCompleted(this, new GetVideosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/GetQuestion", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Question GetQuestion(int id) {
            object[] results = this.Invoke("GetQuestion", new object[] {
                        id});
            return ((Question)(results[0]));
        }
        
        public System.IAsyncResult BeginGetQuestion(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetQuestion", new object[] {
                        id}, callback, asyncState);
        }
        
        public Question EndGetQuestion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Question)(results[0]));
        }
        
        public void GetQuestionAsync(int id) {
            this.GetQuestionAsync(id, null);
        }
        
        public void GetQuestionAsync(int id, object userState) {
            if ((this.GetQuestionOperationCompleted == null)) {
                this.GetQuestionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQuestionCompleted);
            }
            this.InvokeAsync("GetQuestion", new object[] {
                        id}, this.GetQuestionOperationCompleted, userState);
        }
        
        private void OnGetQuestionCompleted(object arg) {
            if ((this.GetQuestionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQuestionCompleted(this, new GetQuestionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/GetQuiz", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Quiz GetQuiz(int anzahlFragen) {
            object[] results = this.Invoke("GetQuiz", new object[] {
                        anzahlFragen});
            return ((Quiz)(results[0]));
        }
        
        public System.IAsyncResult BeginGetQuiz(int anzahlFragen, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetQuiz", new object[] {
                        anzahlFragen}, callback, asyncState);
        }
        
        public Quiz EndGetQuiz(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Quiz)(results[0]));
        }
        
        public void GetQuizAsync(int anzahlFragen) {
            this.GetQuizAsync(anzahlFragen, null);
        }
        
        public void GetQuizAsync(int anzahlFragen, object userState) {
            if ((this.GetQuizOperationCompleted == null)) {
                this.GetQuizOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQuizCompleted);
            }
            this.InvokeAsync("GetQuiz", new object[] {
                        anzahlFragen}, this.GetQuizOperationCompleted, userState);
        }
        
        private void OnGetQuizCompleted(object arg) {
            if ((this.GetQuizCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQuizCompleted(this, new GetQuizCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/ActivateVoucher", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool ActivateVoucher(string fingerprint, int quizId, string code) {
            object[] results = this.Invoke("ActivateVoucher", new object[] {
                        fingerprint,
                        quizId,
                        code});
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginActivateVoucher(string fingerprint, int quizId, string code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ActivateVoucher", new object[] {
                        fingerprint,
                        quizId,
                        code}, callback, asyncState);
        }
        
        public bool EndActivateVoucher(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        public void ActivateVoucherAsync(string fingerprint, int quizId, string code) {
            this.ActivateVoucherAsync(fingerprint, quizId, code, null);
        }
        
        public void ActivateVoucherAsync(string fingerprint, int quizId, string code, object userState) {
            if ((this.ActivateVoucherOperationCompleted == null)) {
                this.ActivateVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateVoucherCompleted);
            }
            this.InvokeAsync("ActivateVoucher", new object[] {
                        fingerprint,
                        quizId,
                        code}, this.ActivateVoucherOperationCompleted, userState);
        }
        
        private void OnActivateVoucherCompleted(object arg) {
            if ((this.ActivateVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateVoucherCompleted(this, new ActivateVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://loewenbraeuservice.ip-connect.de/DischargeVoucher", RequestNamespace="http://loewenbraeuservice.ip-connect.de/", ResponseNamespace="http://loewenbraeuservice.ip-connect.de/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool DischargeVoucher(string fingerprint, int quizId, string code) {
            object[] results = this.Invoke("DischargeVoucher", new object[] {
                        fingerprint,
                        quizId,
                        code});
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginDischargeVoucher(string fingerprint, int quizId, string code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DischargeVoucher", new object[] {
                        fingerprint,
                        quizId,
                        code}, callback, asyncState);
        }
        
        public bool EndDischargeVoucher(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        public void DischargeVoucherAsync(string fingerprint, int quizId, string code) {
            this.DischargeVoucherAsync(fingerprint, quizId, code, null);
        }
        
        public void DischargeVoucherAsync(string fingerprint, int quizId, string code, object userState) {
            if ((this.DischargeVoucherOperationCompleted == null)) {
                this.DischargeVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDischargeVoucherCompleted);
            }
            this.InvokeAsync("DischargeVoucher", new object[] {
                        fingerprint,
                        quizId,
                        code}, this.DischargeVoucherOperationCompleted, userState);
        }
        
        private void OnDischargeVoucherCompleted(object arg) {
            if ((this.DischargeVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DischargeVoucherCompleted(this, new DischargeVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class DishesOfTheDay {
        
        private category[] dishOfTheDayField;
        
        /// <remarks/>
        public category[] DishOfTheDay {
            get {
                return this.dishOfTheDayField;
            }
            set {
                this.dishOfTheDayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class category {
        
        private string titleField;
        
        private dish[] dishesField;
        
        private string subtitleField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public dish[] Dishes {
            get {
                return this.dishesField;
            }
            set {
                this.dishesField = value;
            }
        }
        
        /// <remarks/>
        public string Subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class dish {
        
        private string headlineField;
        
        private string descriptionField;
        
        private string priceField;
        
        /// <remarks/>
        public string Headline {
            get {
                return this.headlineField;
            }
            set {
                this.headlineField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class Reservation {
        
        private string reservationIdField;
        
        private System.DateTime reservationTimeField;
        
        private string fingerprintField2;
        
        private string mobileField1;
        
        private string guestNameField;
        
        private int seatsField1;
        
        private string adviceField1;
        
        private string confirmCodeField;
        
        private StatusArt statusField;
        
        private string declineReasonField;
        
        private System.DateTime lastChangeField;
        
        /// <remarks/>
        public string ReservationId {
            get {
                return this.reservationIdField;
            }
            set {
                this.reservationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReservationTime {
            get {
                return this.reservationTimeField;
            }
            set {
                this.reservationTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Fingerprint {
            get {
                return this.fingerprintField2;
            }
            set {
                this.fingerprintField2 = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField1;
            }
            set {
                this.mobileField1 = value;
            }
        }
        
        /// <remarks/>
        public string GuestName {
            get {
                return this.guestNameField;
            }
            set {
                this.guestNameField = value;
            }
        }
        
        /// <remarks/>
        public int Seats {
            get {
                return this.seatsField1;
            }
            set {
                this.seatsField1 = value;
            }
        }
        
        /// <remarks/>
        public string Advice {
            get {
                return this.adviceField1;
            }
            set {
                this.adviceField1 = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmCode {
            get {
                return this.confirmCodeField;
            }
            set {
                this.confirmCodeField = value;
            }
        }
        
        /// <remarks/>
        public StatusArt Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string DeclineReason {
            get {
                return this.declineReasonField;
            }
            set {
                this.declineReasonField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastChange {
            get {
                return this.lastChangeField;
            }
            set {
                this.lastChangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public enum StatusArt {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Requested,
        
        /// <remarks/>
        ConfirmedByRestaurant,
        
        /// <remarks/>
        ConfirmedByCustomer,
        
        /// <remarks/>
        DeclinedByRestaurant,
        
        /// <remarks/>
        DeclinedAfterConfirmedByRestaurant,
        
        /// <remarks/>
        AbortedByCustomer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class Event {
        
        private System.DateTime activatedAtField;
        
        private string dateField;
        
        private System.DateTime dateOrderField;
        
        private string descriptionField1;
        
        private System.DateTime expiresAtField;
        
        private bool isActivatedField;
        
        private string reservationLinkField;
        
        private string thumbnailLinkField;
        
        private string titleField1;
        
        /// <remarks/>
        public System.DateTime ActivatedAt {
            get {
                return this.activatedAtField;
            }
            set {
                this.activatedAtField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOrder {
            get {
                return this.dateOrderField;
            }
            set {
                this.dateOrderField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField1;
            }
            set {
                this.descriptionField1 = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActivated {
            get {
                return this.isActivatedField;
            }
            set {
                this.isActivatedField = value;
            }
        }
        
        /// <remarks/>
        public string ReservationLink {
            get {
                return this.reservationLinkField;
            }
            set {
                this.reservationLinkField = value;
            }
        }
        
        /// <remarks/>
        public string ThumbnailLink {
            get {
                return this.thumbnailLinkField;
            }
            set {
                this.thumbnailLinkField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField1;
            }
            set {
                this.titleField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class Picture {
        
        private string descriptionField2;
        
        private string fileNameField;
        
        private string linkField;
        
        private int sortOrderField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField2;
            }
            set {
                this.descriptionField2 = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public int SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class Video {
        
        private string descriptionField3;
        
        private string fileNameField1;
        
        private string linkField1;
        
        private int sortOrderField1;
        
        private string thumbnailLinkField1;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField3;
            }
            set {
                this.descriptionField3 = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField1;
            }
            set {
                this.fileNameField1 = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField1;
            }
            set {
                this.linkField1 = value;
            }
        }
        
        /// <remarks/>
        public int SortOrder {
            get {
                return this.sortOrderField1;
            }
            set {
                this.sortOrderField1 = value;
            }
        }
        
        /// <remarks/>
        public string ThumbnailLink {
            get {
                return this.thumbnailLinkField1;
            }
            set {
                this.thumbnailLinkField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class Question {
        
        private Answer[] answersField;
        
        private string descriptionField5;
        
        private int numberField;
        
        private int pointsField;
        
        private Serie serieField;
        
        private long serieIdField;
        
        /// <remarks/>
        public Answer[] Answers {
            get {
                return this.answersField;
            }
            set {
                this.answersField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField5;
            }
            set {
                this.descriptionField5 = value;
            }
        }
        
        /// <remarks/>
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public int Points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        public Serie Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public long SerieId {
            get {
                return this.serieIdField;
            }
            set {
                this.serieIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class Answer {
        
        private int idField;
        
        private string descriptionField4;
        
        private string explanationField;
        
        private bool isRightField;
        
        private int questionIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField4;
            }
            set {
                this.descriptionField4 = value;
            }
        }
        
        /// <remarks/>
        public string Explanation {
            get {
                return this.explanationField;
            }
            set {
                this.explanationField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRight {
            get {
                return this.isRightField;
            }
            set {
                this.isRightField = value;
            }
        }
        
        /// <remarks/>
        public int QuestionId {
            get {
                return this.questionIdField;
            }
            set {
                this.questionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class Serie {
        
        private System.DateTime activatedAtField1;
        
        private string descriptionField6;
        
        private System.DateTime expiresAtField1;
        
        private bool isActivatedField1;
        
        /// <remarks/>
        public System.DateTime ActivatedAt {
            get {
                return this.activatedAtField1;
            }
            set {
                this.activatedAtField1 = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField6;
            }
            set {
                this.descriptionField6 = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField1;
            }
            set {
                this.expiresAtField1 = value;
            }
        }
        
        /// <remarks/>
        public bool IsActivated {
            get {
                return this.isActivatedField1;
            }
            set {
                this.isActivatedField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loewenbraeuservice.ip-connect.de/")]
    public partial class Quiz {
        
        private Question[] questionsField;
        
        private int pointsProAnswerField;
        
        private int idField2;
        
        /// <remarks/>
        public Question[] Questions {
            get {
                return this.questionsField;
            }
            set {
                this.questionsField = value;
            }
        }
        
        /// <remarks/>
        public int PointsProAnswer {
            get {
                return this.pointsProAnswerField;
            }
            set {
                this.pointsProAnswerField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField2;
            }
            set {
                this.idField2 = value;
            }
        }
    }
    
    public partial class TodaysMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodaysMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DishesOfTheDay Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DishesOfTheDay)(this.results[0]));
            }
        }
    }
    
    public delegate void TodaysMenuCompletedEventHandler(object sender, TodaysMenuCompletedEventArgs args);
    
    public partial class CreateReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void CreateReservationCompletedEventHandler(object sender, CreateReservationCompletedEventArgs args);
    
    public partial class GetReservationByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReservationByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Reservation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reservation)(this.results[0]));
            }
        }
    }
    
    public delegate void GetReservationByIdCompletedEventHandler(object sender, GetReservationByIdCompletedEventArgs args);
    
    public partial class CreateReservationByObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateReservationByObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void CreateReservationByObjectCompletedEventHandler(object sender, CreateReservationByObjectCompletedEventArgs args);
    
    public partial class SetReservationConfirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReservationConfirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    public delegate void SetReservationConfirmCompletedEventHandler(object sender, SetReservationConfirmCompletedEventArgs args);
    
    public partial class IsDeclinedByRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsDeclinedByRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    public delegate void IsDeclinedByRestaurantCompletedEventHandler(object sender, IsDeclinedByRestaurantCompletedEventArgs args);
    
    public partial class SetReservationConfirmCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReservationConfirmCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    public delegate void SetReservationConfirmCustomerCompletedEventHandler(object sender, SetReservationConfirmCustomerCompletedEventArgs args);
    
    public partial class SetDecliningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetDecliningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    public delegate void SetDecliningCompletedEventHandler(object sender, SetDecliningCompletedEventArgs args);
    
    public partial class GetReservationsByStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReservationsByStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Reservation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reservation[])(this.results[0]));
            }
        }
    }
    
    public delegate void GetReservationsByStatusCompletedEventHandler(object sender, GetReservationsByStatusCompletedEventArgs args);
    
    public partial class GetEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Event[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Event[])(this.results[0]));
            }
        }
    }
    
    public delegate void GetEventsCompletedEventHandler(object sender, GetEventsCompletedEventArgs args);
    
    public partial class GetPicturesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPicturesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Picture[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Picture[])(this.results[0]));
            }
        }
    }
    
    public delegate void GetPicturesCompletedEventHandler(object sender, GetPicturesCompletedEventArgs args);
    
    public partial class GetVideosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVideosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Video[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Video[])(this.results[0]));
            }
        }
    }
    
    public delegate void GetVideosCompletedEventHandler(object sender, GetVideosCompletedEventArgs args);
    
    public partial class GetQuestionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQuestionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Question Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Question)(this.results[0]));
            }
        }
    }
    
    public delegate void GetQuestionCompletedEventHandler(object sender, GetQuestionCompletedEventArgs args);
    
    public partial class GetQuizCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQuizCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Quiz Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Quiz)(this.results[0]));
            }
        }
    }
    
    public delegate void GetQuizCompletedEventHandler(object sender, GetQuizCompletedEventArgs args);
    
    public partial class ActivateVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    public delegate void ActivateVoucherCompletedEventHandler(object sender, ActivateVoucherCompletedEventArgs args);
    
    public partial class DischargeVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DischargeVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    public delegate void DischargeVoucherCompletedEventHandler(object sender, DischargeVoucherCompletedEventArgs args);
}
